site_name: ES3011 Experimental Lab
theme: readthedocs
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - toc:
        permalink: True
        separator: "_"
plugins:
    - search
nav:
    - 'Lab Overview': 'lab-overview/index.md'
    - 'Lab Instructions':
        - 'Lab 1': 'lab-docs/lab1.md'
        - 'Lab 2': 'lab-docs/lab2.md'
        - 'Lab 3': 'lab-docs/lab3.md'
        - 'Lab 4': 'lab-docs/lab4.md'
        - 'Lab 5': 'lab-docs/lab5.md'
        - 'Lab 6': 'lab-docs/lab6.md'
        - 'Lab 7': 'lab-docs/lab7.md'

extra_css: [theme_override.css]
